# Generated by Django 2.0.2 on 2018-10-19 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='dummy_city', max_length=50, verbose_name='Name')),
                ('lon', models.DecimalField(decimal_places=12, max_digits=20, verbose_name='Longitude')),
                ('lat', models.DecimalField(decimal_places=12, max_digits=20, verbose_name='Latitude')),
                ('deaths', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Dam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='dummy_dam', max_length=50, verbose_name='Name')),
                ('lon', models.DecimalField(decimal_places=12, max_digits=20, verbose_name='Longitude')),
                ('lat', models.DecimalField(decimal_places=12, max_digits=20, verbose_name='Latitude')),
                ('river', models.CharField(default='river', max_length=50, verbose_name='River')),
                ('area', models.CharField(default='dummy_area', max_length=50, verbose_name='Area')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='dummy_state', max_length=50, verbose_name='Name')),
                ('lon', models.DecimalField(decimal_places=12, max_digits=20, verbose_name='Longitude')),
                ('lat', models.DecimalField(decimal_places=12, max_digits=20, verbose_name='Latitude')),
                ('deaths', models.IntegerField(default=0)),
                ('forest_area', models.IntegerField(default=0, verbose_name='Forest Area(in sq.km)')),
                ('forest_per', models.DecimalField(decimal_places=3, default=0.0, max_digits=6, verbose_name='Forest Percentage')),
            ],
        ),
        migrations.AddField(
            model_name='dam',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cope_with_disaster.State'),
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cope_with_disaster.State'),
        ),
    ]
