# Generated by Django 2.0.2 on 2018-10-23 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cope_with_disaster', '0002_auto_20181021_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
    ]
